---

- block:

  - name: FileBeat Yum Repository
    copy:
      dest:    "/etc/yum.repos.d/filebeat-{{filebeat_version}}.repo"
      content: "{{filebeat_yum_config}}"
      owner:   "root"
      group:   "root"
      mode:    "0644"

  - name: Install FileBeat (RedHat)
    yum:
      state: "{{ (filebeat_upgrade) | ternary('latest', 'present') }}"
      name: "{{filebeat_package}}"
      update_cache: yes
    notify: filebeat restart

  when: filebeat_use_repo

- block:

  - name: Download FileBeat RPM
    get_url:
      url: "{{filebeat_package_url}}"
      dest: "/var/cache/yum/{{ansible_architecture}}/filebeat-{{filebeat_version}}-{{ansible_architecture}}.rpm"

  - name: Install FileBeat from RPM
    yum:
      state: present
      name: "/var/cache/yum/{{ansible_architecture}}/filebeat-{{filebeat_version}}-{{ansible_architecture}}.rpm"
    notify: filebeat restart

  when: not filebeat_use_repo


# vi:ts=2:sw=2:et:ft=yaml
